export const FETCH_PICTURES_REQUEST = 'FETCH_PICTURES_REQUEST';
export const FETCH_PICTURES_ERROR = 'FETCH_PICTURES_ERROR';
export const FETCH_PICTURES_SUCCESS = 'FETCH_PICTURES_SUCCESS';
export const SELECT_NEXT_PICTURE = 'SELECT_NEXT_PICTURE';
export const SELECT_PREVIOUS_PICTURE = 'SELECT_PREVIOUS_PICTURE';
export const SELECT_PICTURE = 'SELECT_PICTURE';
